//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchDictator.Web.Resources.OrgNameParts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrgNameVerbs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrgNameVerbs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunchDictator.Web.Resources.OrgNameParts.OrgNameVerbs", typeof(OrgNameVerbs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumping.
        /// </summary>
        internal static string Verb1 {
            get {
                return ResourceManager.GetString("Verb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hugging.
        /// </summary>
        internal static string Verb10 {
            get {
                return ResourceManager.GetString("Verb10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bushwhacking.
        /// </summary>
        internal static string Verb2 {
            get {
                return ResourceManager.GetString("Verb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singing.
        /// </summary>
        internal static string Verb3 {
            get {
                return ResourceManager.GetString("Verb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prancing.
        /// </summary>
        internal static string Verb4 {
            get {
                return ResourceManager.GetString("Verb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancing.
        /// </summary>
        internal static string Verb5 {
            get {
                return ResourceManager.GetString("Verb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lollygagging.
        /// </summary>
        internal static string Verb6 {
            get {
                return ResourceManager.GetString("Verb6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creeping.
        /// </summary>
        internal static string Verb7 {
            get {
                return ResourceManager.GetString("Verb7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duelling.
        /// </summary>
        internal static string Verb8 {
            get {
                return ResourceManager.GetString("Verb8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploding.
        /// </summary>
        internal static string Verb9 {
            get {
                return ResourceManager.GetString("Verb9", resourceCulture);
            }
        }
    }
}
