//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchDictator.Web.Resources.OrgNameParts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrgNameArticles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrgNameArticles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunchDictator.Web.Resources.OrgNameParts.OrgNameArticles", typeof(OrgNameArticles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        internal static string Article1 {
            get {
                return ResourceManager.GetString("Article1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These.
        /// </summary>
        internal static string Article2 {
            get {
                return ResourceManager.GetString("Article2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Few.
        /// </summary>
        internal static string Article3 {
            get {
                return ResourceManager.GetString("Article3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half A Dozen.
        /// </summary>
        internal static string Article4 {
            get {
                return ResourceManager.GetString("Article4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some.
        /// </summary>
        internal static string Article5 {
            get {
                return ResourceManager.GetString("Article5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Hatful Of.
        /// </summary>
        internal static string Article6 {
            get {
                return ResourceManager.GetString("Article6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Worrisome Number Of.
        /// </summary>
        internal static string Article7 {
            get {
                return ResourceManager.GetString("Article7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousands Of.
        /// </summary>
        internal static string Article8 {
            get {
                return ResourceManager.GetString("Article8", resourceCulture);
            }
        }
    }
}
