// <auto-generated />
namespace LunchDictator.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddPlacesToDictatorship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPlacesToDictatorship));
        
        string IMigrationMetadata.Id
        {
            get { return "201410011841259_AddPlacesToDictatorship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
