//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchDictator.Web.Resources.DictatorshipNameParts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DictatorshipNamePluralNouns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictatorshipNamePluralNouns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunchDictator.Web.Resources.DictatorshipNameParts.DictatorshipNamePluralNouns", typeof(DictatorshipNamePluralNouns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnomes.
        /// </summary>
        internal static string Noun1 {
            get {
                return ResourceManager.GetString("Noun1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerfherders.
        /// </summary>
        internal static string Noun10 {
            get {
                return ResourceManager.GetString("Noun10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunnies.
        /// </summary>
        internal static string Noun11 {
            get {
                return ResourceManager.GetString("Noun11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robots.
        /// </summary>
        internal static string Noun12 {
            get {
                return ResourceManager.GetString("Noun12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombies.
        /// </summary>
        internal static string Noun13 {
            get {
                return ResourceManager.GetString("Noun13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervillains.
        /// </summary>
        internal static string Noun14 {
            get {
                return ResourceManager.GetString("Noun14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superheroes.
        /// </summary>
        internal static string Noun15 {
            get {
                return ResourceManager.GetString("Noun15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Developers.
        /// </summary>
        internal static string Noun16 {
            get {
                return ResourceManager.GetString("Noun16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragons.
        /// </summary>
        internal static string Noun2 {
            get {
                return ResourceManager.GetString("Noun2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninjas.
        /// </summary>
        internal static string Noun3 {
            get {
                return ResourceManager.GetString("Noun3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girls.
        /// </summary>
        internal static string Noun4 {
            get {
                return ResourceManager.GetString("Noun4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boys.
        /// </summary>
        internal static string Noun5 {
            get {
                return ResourceManager.GetString("Noun5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancers.
        /// </summary>
        internal static string Noun6 {
            get {
                return ResourceManager.GetString("Noun6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighters.
        /// </summary>
        internal static string Noun7 {
            get {
                return ResourceManager.GetString("Noun7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicorns.
        /// </summary>
        internal static string Noun8 {
            get {
                return ResourceManager.GetString("Noun8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llamas.
        /// </summary>
        internal static string Noun9 {
            get {
                return ResourceManager.GetString("Noun9", resourceCulture);
            }
        }
    }
}
