//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchDictator.Web.Resources.DictatorshipNameParts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DictatorshipNameAdjectives {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictatorshipNameAdjectives() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunchDictator.Web.Resources.DictatorshipNameParts.DictatorshipNameAdjectives", typeof(DictatorshipNameAdjectives).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcadian.
        /// </summary>
        internal static string Adjective1 {
            get {
                return ResourceManager.GetString("Adjective1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabulous.
        /// </summary>
        internal static string Adjective10 {
            get {
                return ResourceManager.GetString("Adjective10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminous.
        /// </summary>
        internal static string Adjective11 {
            get {
                return ResourceManager.GetString("Adjective11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neon.
        /// </summary>
        internal static string Adjective12 {
            get {
                return ResourceManager.GetString("Adjective12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect.
        /// </summary>
        internal static string Adjective13 {
            get {
                return ResourceManager.GetString("Adjective13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adorable.
        /// </summary>
        internal static string Adjective14 {
            get {
                return ResourceManager.GetString("Adjective14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gargantuan.
        /// </summary>
        internal static string Adjective15 {
            get {
                return ResourceManager.GetString("Adjective15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniscule.
        /// </summary>
        internal static string Adjective16 {
            get {
                return ResourceManager.GetString("Adjective16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegant.
        /// </summary>
        internal static string Adjective17 {
            get {
                return ResourceManager.GetString("Adjective17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnificent.
        /// </summary>
        internal static string Adjective18 {
            get {
                return ResourceManager.GetString("Adjective18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugly.
        /// </summary>
        internal static string Adjective19 {
            get {
                return ResourceManager.GetString("Adjective19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpulent.
        /// </summary>
        internal static string Adjective2 {
            get {
                return ResourceManager.GetString("Adjective2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mysterious.
        /// </summary>
        internal static string Adjective20 {
            get {
                return ResourceManager.GetString("Adjective20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnoxious.
        /// </summary>
        internal static string Adjective21 {
            get {
                return ResourceManager.GetString("Adjective21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repulsive.
        /// </summary>
        internal static string Adjective22 {
            get {
                return ResourceManager.GetString("Adjective22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        internal static string Adjective23 {
            get {
                return ResourceManager.GetString("Adjective23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obedient.
        /// </summary>
        internal static string Adjective24 {
            get {
                return ResourceManager.GetString("Adjective24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witty.
        /// </summary>
        internal static string Adjective25 {
            get {
                return ResourceManager.GetString("Adjective25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        internal static string Adjective26 {
            get {
                return ResourceManager.GetString("Adjective26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huge.
        /// </summary>
        internal static string Adjective27 {
            get {
                return ResourceManager.GetString("Adjective27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skinny.
        /// </summary>
        internal static string Adjective28 {
            get {
                return ResourceManager.GetString("Adjective28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whispering.
        /// </summary>
        internal static string Adjective29 {
            get {
                return ResourceManager.GetString("Adjective29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turgid.
        /// </summary>
        internal static string Adjective3 {
            get {
                return ResourceManager.GetString("Adjective3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient.
        /// </summary>
        internal static string Adjective30 {
            get {
                return ResourceManager.GetString("Adjective30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        internal static string Adjective31 {
            get {
                return ResourceManager.GetString("Adjective31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Adjective32 {
            get {
                return ResourceManager.GetString("Adjective32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Democratic.
        /// </summary>
        internal static string Adjective33 {
            get {
                return ResourceManager.GetString("Adjective33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundamentalist.
        /// </summary>
        internal static string Adjective34 {
            get {
                return ResourceManager.GetString("Adjective34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenacious.
        /// </summary>
        internal static string Adjective4 {
            get {
                return ResourceManager.GetString("Adjective4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petulant.
        /// </summary>
        internal static string Adjective5 {
            get {
                return ResourceManager.GetString("Adjective5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insolent.
        /// </summary>
        internal static string Adjective6 {
            get {
                return ResourceManager.GetString("Adjective6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feckless.
        /// </summary>
        internal static string Adjective7 {
            get {
                return ResourceManager.GetString("Adjective7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calamitous.
        /// </summary>
        internal static string Adjective8 {
            get {
                return ResourceManager.GetString("Adjective8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abhorrent.
        /// </summary>
        internal static string Adjective9 {
            get {
                return ResourceManager.GetString("Adjective9", resourceCulture);
            }
        }
    }
}
