//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchDictator.Web.Resources.DictatorshipNameParts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DictatorshipNameStateType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictatorshipNameStateType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunchDictator.Web.Resources.DictatorshipNameParts.DictatorshipNameStateType", typeof(DictatorshipNameStateType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Republic.
        /// </summary>
        internal static string StateType1 {
            get {
                return ResourceManager.GetString("StateType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictatorship.
        /// </summary>
        internal static string StateType10 {
            get {
                return ResourceManager.GetString("StateType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        internal static string StateType2 {
            get {
                return ResourceManager.GetString("StateType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateType3 {
            get {
                return ResourceManager.GetString("StateType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principality.
        /// </summary>
        internal static string StateType4 {
            get {
                return ResourceManager.GetString("StateType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protectorate.
        /// </summary>
        internal static string StateType5 {
            get {
                return ResourceManager.GetString("StateType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colony.
        /// </summary>
        internal static string StateType6 {
            get {
                return ResourceManager.GetString("StateType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federation.
        /// </summary>
        internal static string StateType7 {
            get {
                return ResourceManager.GetString("StateType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory.
        /// </summary>
        internal static string StateType8 {
            get {
                return ResourceManager.GetString("StateType8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empire.
        /// </summary>
        internal static string StateType9 {
            get {
                return ResourceManager.GetString("StateType9", resourceCulture);
            }
        }
    }
}
