//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchDictator.Web.Resources.DictatorshipNameParts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DictatorshipNameVerbs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictatorshipNameVerbs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunchDictator.Web.Resources.DictatorshipNameParts.DictatorshipNameVerbs", typeof(DictatorshipNameVerbs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riders.
        /// </summary>
        internal static string Verb1 {
            get {
                return ResourceManager.GetString("Verb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huggers.
        /// </summary>
        internal static string Verb10 {
            get {
                return ResourceManager.GetString("Verb10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainers.
        /// </summary>
        internal static string Verb11 {
            get {
                return ResourceManager.GetString("Verb11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torturers.
        /// </summary>
        internal static string Verb12 {
            get {
                return ResourceManager.GetString("Verb12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lickers.
        /// </summary>
        internal static string Verb13 {
            get {
                return ResourceManager.GetString("Verb13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouncers.
        /// </summary>
        internal static string Verb14 {
            get {
                return ResourceManager.GetString("Verb14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washers.
        /// </summary>
        internal static string Verb15 {
            get {
                return ResourceManager.GetString("Verb15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eaters.
        /// </summary>
        internal static string Verb16 {
            get {
                return ResourceManager.GetString("Verb16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shavers.
        /// </summary>
        internal static string Verb17 {
            get {
                return ResourceManager.GetString("Verb17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratchers.
        /// </summary>
        internal static string Verb18 {
            get {
                return ResourceManager.GetString("Verb18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturers.
        /// </summary>
        internal static string Verb19 {
            get {
                return ResourceManager.GetString("Verb19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bushwhackers.
        /// </summary>
        internal static string Verb2 {
            get {
                return ResourceManager.GetString("Verb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductors.
        /// </summary>
        internal static string Verb20 {
            get {
                return ResourceManager.GetString("Verb20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singers.
        /// </summary>
        internal static string Verb3 {
            get {
                return ResourceManager.GetString("Verb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prancers.
        /// </summary>
        internal static string Verb4 {
            get {
                return ResourceManager.GetString("Verb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancers.
        /// </summary>
        internal static string Verb5 {
            get {
                return ResourceManager.GetString("Verb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throwers.
        /// </summary>
        internal static string Verb6 {
            get {
                return ResourceManager.GetString("Verb6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        internal static string Verb7 {
            get {
                return ResourceManager.GetString("Verb7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duellers.
        /// </summary>
        internal static string Verb8 {
            get {
                return ResourceManager.GetString("Verb8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploders.
        /// </summary>
        internal static string Verb9 {
            get {
                return ResourceManager.GetString("Verb9", resourceCulture);
            }
        }
    }
}
